local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 1.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.05          # increase to for higher res 0.025
  transform_tolerance: 0.5  # tune, latency in published transforms (in seconds)
  cost_scaling_factor: 5    # tune, cost scaling factor
  inflation_radius: 0.55    # tune, distance at which the cost of an obstacle should be considered.
